import { ProjectCardProps } from "@/lib/interfaces/project-card-props";

export const Projects: ProjectCardProps[] = [
  {
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/radium-favicon.png",
    title: "Radium",
    description: "Empowering Developers to Rapidly Ship Projects.",
    stage: "Alpha",
    date: "7.6.2024",
    summary:
      "Radium, the single platform designed to empower developers, whether they are beginners or professionals. Radium offers a comprehensive suite of tools and services crafted to streamline the development process, ensuring a swift and efficient delivery of projects.",
    official: "https://radium.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
  },
  {
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
    title: "Silvi",
    description: "The Personal Assistant.",
    stage: "Development",
    date: "7.7.2024",
    summary:
      "Introducing Silvi - your ultimate personal assistant. Whether you need help with tasks, information, updates, or simply want to perform any simple every day task with your digital goods.. Say goodbye to juggling between different assistants – Silvi is here to simplify your life...",
    official: "https://silvi.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
  },
  {
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
    title: "Prison",
    description: "The Next Gen Authentication System.",
    stage: "Development",
    date: "Upcoming",
    summary:
      "Prison, The Next Gen Authentication System. Picture a world where your online identity is safeguarded where passwords are a thing of the past. Prison combines the best elements of leading password managers with the simplicity of passwordless logins, ensuring your accounts are impenetrable yet effortlessly accessible. Bid farewell to the hassle of remembering passwords and embrace a new era of seamless, fortified authentication. With Prison, your digital fortress awaits.",
    official: "https://prison.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
  },
  {
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
    title: "Capital",
    description: "The Personal Finance Assistant.",
    stage: "Development",
    date: "Upcoming",
    summary:
      "Capital, The Personal Finance Assistant. Designed to revolutionize the way you manage your money. Capital seamlessly integrates budgeting, expense tracking, and investment management into one intuitive platform. With Capital by your side, you'll gain insights into your spending habits, set achievable financial goals, and watch your wealth grow. Take control of your finances and unlock your financial potential with Capital. It's not just an assistant; it's personal finance assistant.",
    official: "https://capital.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
  },
];

export const BranchedProjects: ProjectCardProps[] = [
  {
    title: "Parser",
    description: "The Markdown Processor for LLM Responses..",
    stage: "Development",
    date: "Upcoming",
    summary:
      "Parser is a powerful and efficient Markdown processor designed specifically for handling LLM (Large Language Model) responses. This innovative tool simplifies the formatting and parsing of text generated by LLMs, ensuring a seamless integration into various applications and platforms. With Parser, you can effortlessly transform raw LLM responses into well-structured and visually appealing content.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://github.com/vgseven/parser",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
  },
  {
    title: "Writer",
    description: "Next Gen Online Writer...",
    stage: "Development",
    date: "Upcoming",
    summary:
      "Introducing Writer, the Next Gen Online Writer that revolutionizes the way we create and engage with content. This cutting-edge platform combines advanced writing tools with a user-friendly interface, empowering users to unleash their creativity effortlessly. Whether you're a professional writer, a content creator, or someone passionate about expressing ideas, Writer is your go-to solution for crafting captivating and polished content in the digital age. Elevate your writing experience with Writer - where innovation meets inspiration.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://github.com/vgseven/writer",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
  },
  {
    title: "Edith",
    description: "Web Scraping Engine built in Rust...",
    stage: "Development",
    date: "Upcoming",
    summary:
      "Edith is a high-performance Web Scraping Engine meticulously crafted in Rust, combining the robustness of the Rust language with the efficiency required for web data extraction. With Edith, you have a versatile tool at your fingertips, offering unparalleled speed and reliability in harvesting data from the web. Its Rust-based architecture ensures both safety and speed, making Edith a go-to solution for developers seeking a powerful and secure web scraping engine.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://github.com/vgseven/edith",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/vgseven-company/silver-favicon.png",
  },
];
