import { ProjectCardProps } from "@/lib/schemas/project-card-props";

export const SacredProjectCards: ProjectCardProps[] = [
  {
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/radium/radium-favicon.png",
    title: "Radium",
    description: "Empowering Developers to Rapidly Ship Projects.",
    stage: "Live",
    date: "27.12.2023",
    timeline: "Sacred",
    summary:
      "Welcome to Radium, the single platform designed to empower developers, whether they are beginners or professionals. Radium offers a comprehensive suite of tools and services crafted to streamline the development process, ensuring a swift and efficient delivery of projects.",
    official: "https://radium.vgseven.com/",
    knowMore: "https://github.com/silver-company/radium",
    findUpdates: "https://x.com/vgsevenn",
  },
];

export const BranchedProjectCards: ProjectCardProps[] = [
  {
    title: "Crystal",
    description: "The Next Generation Object Storage Services..",
    stage: "In-Development",
    date: "Upcoming",
    timeline: "Branched",
  },
  {
    title: "Silvi",
    description: "The Personal Assistant..",
    stage: "In-Development",
    date: "Upcoming",
    timeline: "Branched",
  },
  {
    title: "Einfi",
    description: "Everything of Everything Platform..",
    stage: "Pre-Development",
    date: "Upcoming",
    timeline: "Branched",
  },
];

export const ForkedProjectCards: ProjectCardProps[] = [
  {
    title: "Parser",
    description: "The Markdown Processor for LLM Responses..",
    stage: "In-Development",
    date: "Upcoming",
    timeline: "Forked",
    summary:
      "Parser is a powerful and efficient Markdown processor designed specifically for handling LLM (Large Language Model) responses. This innovative tool simplifies the formatting and parsing of text generated by LLMs, ensuring a seamless integration into various applications and platforms. With Parser, you can effortlessly transform raw LLM responses into well-structured and visually appealing content.",
    findUpdates: "https://x.com/vgsevenn",
    knowMore: "https://github.com/vgseven/parser",
    official: "https://github.com/vgseven/parser",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/silver-company/silver-profile.png",
  },
  {
    title: "Writer",
    description: "Next Gen Online Writer...",
    stage: "In-Development",
    date: "Upcoming",
    timeline: "Forked",
    summary:
      "Introducing Writer, the Next Gen Online Writer that revolutionizes the way we create and engage with content. This cutting-edge platform combines advanced writing tools with a user-friendly interface, empowering users to unleash their creativity effortlessly. Whether you're a professional writer, a content creator, or someone passionate about expressing ideas, Writer is your go-to solution for crafting captivating and polished content in the digital age. Elevate your writing experience with Writer - where innovation meets inspiration.",
    findUpdates: "https://x.com/vgsevenn",
    knowMore: "https://github.com/vgseven/writer",
    official: "https://writer.vgseven.com/",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/silver-company/silver-profile.png",
  },
  {
    title: "Edith",
    description: "Web Scraping Engine built in Rust...",
    stage: "In-Development",
    date: "Upcoming",
    timeline: "Forked",
    summary:
      "Edith is a high-performance Web Scraping Engine meticulously crafted in Rust, combining the robustness of the Rust language with the efficiency required for web data extraction. With Edith, you have a versatile tool at your fingertips, offering unparalleled speed and reliability in harvesting data from the web. Its Rust-based architecture ensures both safety and speed, making Edith a go-to solution for developers seeking a powerful and secure web scraping engine.",
    findUpdates: "https://x.com/vgsevenn",
    knowMore: "https://github.com/vgseven/edith",
    official: "https://github.com/vgseven/edith",
    profile:
      "https://eo4grnhr9puxdgdq.public.blob.vercel-storage.com/silver-company/silver-profile.png",
  },
];
