import { ProjectCardProps } from "@/lib/interfaces/project-card-props";

export const Projects: ProjectCardProps[] = [
  {
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/titanium/titanium-favicon.png",
    title: "Titanium",
    description: "Titanium, Redefining the Security with Modern Architecture.",
    stage: "Development",
    launchDate: "07.06.24",
    summary:
      "Titanium is a next-generation password manager platform designed to provide redefined security with ease of use. By leveraging Argon2 for password hashing and AES for data encryption, Titanium offers the most secure password management service you can trust blindly.",
    official: "https://titanium.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
    newUpdate: "Titanium is too close to move in Alpha Stage, Shiping Soon..",
  },
  {
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/radium/radium-favicon.png",
    title: "Radium",
    description: "Radium, Empowering Developers to Rapidly Ship Projects.",
    stage: "Development",
    launchDate: "17.06.24",
    summary:
      "Introducing Radium – the ultimate platform for developers, whether you're just starting out or a pro. Radium gives you everything you need to make coding easier and faster. It's like having all your tools in one place, from writing code to managing projects. With Radium, you can tackle any project with confidence and get things done in no time. Say hello to Radium and make coding a breeze!",
    official: "https://radium.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
    newUpdate: "Radium, Working on something too special!",
  },
  {
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/silver-company/silver-black-favicon.png",
    title: "Silvi",
    description: "The Personal Assistant.",
    stage: "Development",
    launchDate: "07.07.24",
    summary:
      "Introducing Silvi - your ultimate personal assistant. Whether you need help with tasks, information, updates, or simply want to perform any simple every day task with your digital goods.. Say goodbye to juggling between different assistants – Silvi is here to simplify your life...",
    official: "https://silvi.vgseven.com/",
    findUpdates: "https://x.com/vgsevenn",
    newUpdate: "Silvi, It'll be huge suprise..",
  },
];

export const BranchedProjects: ProjectCardProps[] = [
  {
    title: "Parser",
    description: "The Markdown Processor for LLM Responses..",
    stage: "Development",
    launchDate: "27.02.24",
    summary:
      "Parser is a powerful and efficient Markdown processor designed specifically for handling LLM (Large Language Model) responses. This innovative tool simplifies the formatting and parsing of text generated by LLMs, ensuring a seamless integration into various applications and platforms. With Parser, you can effortlessly transform raw LLM responses into well-structured and visually appealing content.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://github.com/vgseven/parser",
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/silver-company/silver-black-favicon.png",
    newUpdate: "-",
  },
  {
    title: "Writer",
    description: "Next Gen Online Writer...",
    stage: "Development",
    launchDate: "27.02.24",
    summary:
      "Introducing Writer, the Next Gen Online Writer that revolutionizes the way we create and engage with content. This cutting-edge platform combines advanced writing tools with a user-friendly interface, empowering users to unleash their creativity effortlessly. Whether you're a professional writer, a content creator, or someone passionate about expressing ideas, Writer is your go-to solution for crafting captivating and polished content in the digital age. Elevate your writing experience with Writer - where innovation meets inspiration.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://writer.vgseven.com",
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/silver-company/silver-black-favicon.png",
    newUpdate: "-",
  },
  {
    title: "Edith",
    description: "Web Scraping Engine built in Rust...",
    stage: "Development",
    launchDate: "27.02.24",
    summary:
      "Edith is a high-performance Web Scraping Engine meticulously crafted in Rust, combining the robustness of the Rust language with the efficiency required for web data extraction. With Edith, you have a versatile tool at your fingertips, offering unparalleled speed and reliability in harvesting data from the web. Its Rust-based architecture ensures both safety and speed, making Edith a go-to solution for developers seeking a powerful and secure web scraping engine.",
    findUpdates: "https://x.com/vgsevenn",
    official: "https://github.com/vgseven/edith",
    profile:
      "https://odouepjkxheu5esn.public.blob.vercel-storage.com/silver-company/silver-black-favicon.png",
    newUpdate: "-",
  },
];
